export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';

export const BLACKLIST_PRODUCT = 'BLACKLIST_PRODUCT';
export const SUBMIT_LIST = 'SUBMIT_LIST';
export const PURCHASE_LIST = 'PURCHASE_LIST';
